version: "3.7"


services:
    db:
        container_name: famaga-pg
        hostname: db
        image: ankane/pgvector
        ports:
        - 45048:5432
        environment:
            - POSTGRES_DB=famaga
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=5tgb%TGB
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres_db:/var/lib/postgresql/data
        

networks:
  famaga-net:
    driver: bridge


volumes:
  postgres_db:
