FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -U pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the bot code into the container
COPY . .

COPY .env .env

# Command to run the bot
CMD ["python", "spam_job.py"]