services:
    db:
        container_name: famaga-pg
        hostname: db
        image: ankane/pgvector
        ports:
        - 45047:5432
        environment:
            - POSTGRES_DB=famaga
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=5tgb%TGB
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ${HOME}/dumps/famaga_dump.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres_db:/var/lib/postgresql/data
        networks:
            - famaga-net

    bot-app:
        container_name: bot-app
        build:
            context: ../../bot  # Set the context to the 'bot' folder
            dockerfile: ./docker/Dockerfile
        ports:
            - "45041:80"  # Map port 80 in the container to port 45045 on the host
        volumes:
            - "./bot/logs:/app/logs"  # Bind mount for logs
            - type: bind
              source: /root/messages
              target: /app/messages
        environment:
            - DIRECTORY_PATH=/app/messages
            - AGENT_URL=http://fastapi-app:80  # Overriding AGENT_URL to point to the famaga-app service
        networks:
            - famaga-net

    fastapi-app:
        container_name: famaga-app
        build:
            context: ../../
            dockerfile: ./docker/Dockerfile
        ports:
        - "45045:80"
        networks:
            - famaga-net

    crm:
        container_name: crm-admin
        build:
            context: ../../crm/
            dockerfile: ./docker/Dockerfile
        ports:
            - "9027:8000"
        networks:
            - famaga-net

networks:
  famaga-net:
    driver: bridge

volumes:
  postgres_db:
