services:
    db:
        container_name: famaga-pg
        hostname: db
        image: ankane/pgvector
        ports:
        - 45047:5432
        environment:
            - POSTGRES_DB=famaga
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=5tgb%TGB
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ${HOME}/dumps/famaga_dump.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres_db:/var/lib/postgresql/data
        networks:
            - famaga-net

    fastapi-app:
        container_name: famaga-app
        build:
            context: ../../
            dockerfile: ./docker/Dockerfile
        ports:
        - "45045:80"
        networks:
            - famaga-net

    crm:
        container_name: crm-admin
        build:
            context: ../../
            dockerfile: ./crm/docker/Dockerfile
        ports:
            - "9027:8000"
        networks:
            - famaga-net

networks:
  famaga-net:
    driver: bridge

volumes:
  postgres_db:
