"""Initial migration

Revision ID: 1b58112b8d3d
Revises: 
Create Date: 2024-02-16 23:29:41.735195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b58112b8d3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('office_country', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('issue_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('agent_task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('completion_cost', sa.Float(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('agent_type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Failed', 'Passed', 'Stopped', name='statustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.deal_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('issue',
    sa.Column('issue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('issue_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_group_id'], ['issue_group.id'], ),
    sa.PrimaryKeyConstraint('issue_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('from_type', sa.Integer(), nullable=False),
    sa.Column('reply_to', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.deal_id'], ),
    sa.ForeignKeyConstraint(['reply_to'], ['message.message_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('part_inquiry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('full_brand_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.deal_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('intent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('sub_intent', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.message_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('task_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('is_like', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_task.task_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('taskfeedback_issue_link',
    sa.Column('task_feedback_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.issue_id'], ),
    sa.ForeignKeyConstraint(['task_feedback_id'], ['task_feedback.id'], ),
    sa.PrimaryKeyConstraint('task_feedback_id', 'issue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskfeedback_issue_link')
    op.drop_table('task_feedback')
    op.drop_table('intent')
    op.drop_table('part_inquiry')
    op.drop_table('message')
    op.drop_table('issue')
    op.drop_table('agent_task')
    op.drop_table('issue_group')
    op.drop_table('deal')
    # ### end Alembic commands ###
