"""Nullable subject

Revision ID: 53e6c080b076
Revises: b57eaede08bc
Create Date: 2024-04-27 00:52:30.974859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e6c080b076'
down_revision: Union[str, None] = 'b57eaede08bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
