"""Add purchase history

Revision ID: 61e50252005c
Revises: 8d460333ceba
Create Date: 2024-02-23 00:30:01.517192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e50252005c'
down_revision: Union[str, None] = '8d460333ceba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('brand_title', sa.String(), nullable=True),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.Column('client_title', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('requisition_created', sa.DateTime(), nullable=True),
    sa.Column('price_buy', sa.Float(), nullable=True),
    sa.Column('price_sell', sa.Float(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_history')
    # ### end Alembic commands ###
