"""Add completion time

Revision ID: 685a8e5ea59e
Revises: f7cb2f41f538
Create Date: 2024-04-29 12:06:51.134339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685a8e5ea59e'
down_revision: Union[str, None] = 'f7cb2f41f538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('agent_task', sa.Column('action_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_task', 'action_time_ms')

