"""Add uuid

Revision ID: 8dbc1acbd2c6
Revises: 1db19f1e8963
Create Date: 2024-05-06 22:23:36.417843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbc1acbd2c6'
down_revision: Union[str, None] = '1db19f1e8963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('uuid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'runs', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='unique')
    op.drop_column('runs', 'uuid')
    # ### end Alembic commands ###
