"""Change agent task models

Revision ID: b57eaede08bc
Revises: ef5ba9062d47
Create Date: 2024-04-27 00:20:23.299206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57eaede08bc'
down_revision: Union[str, None] = 'ef5ba9062d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_task', sa.Column('action', sa.String(), nullable=True))
    op.alter_column('agent_task', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('agent_task', 'agent_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_task', sa.Column('agent_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('agent_task', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('agent_task', 'action')

