"""Add more nulls

Revision ID: ea5f01170678
Revises: 574546e72e52
Create Date: 2024-02-17 02:32:29.597544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5f01170678'
down_revision: Union[str, None] = '574546e72e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('part_inquiry', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('part_inquiry', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('part_inquiry', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('part_inquiry', 'part_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('part_inquiry', 'part_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('part_inquiry', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('part_inquiry', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('part_inquiry', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
