"""Add deal relation

Revision ID: ef5ba9062d47
Revises: a024b9ffe32f
Create Date: 2024-04-26 23:50:23.050744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5ba9062d47'
down_revision: Union[str, None] = 'a024b9ffe32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_task', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent_task', 'runs', ['run_id'], ['run_id'])
    op.add_column('runs', sa.Column('deal_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'runs', 'deal', ['deal_id'], ['deal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'deal_id')
    op.drop_constraint(None, 'agent_task', type_='foreignkey')
    op.drop_column('agent_task', 'run_id')

    # ### end Alembic commands ###
