"""Add error field

Revision ID: f7cb2f41f538
Revises: 02159fd4de2a
Create Date: 2024-04-29 11:55:34.874465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cb2f41f538'
down_revision: Union[str, None] = '02159fd4de2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_task', sa.Column('error', sa.String(), nullable=True))
    op.alter_column('runs', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'status',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('agent_task', 'error')
