# Generated by Django 5.0.3 on 2024-03-26 05:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='deal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.deal'),
            preserve_default=False,
        ),
    ]
