# Generated by Django 5.0.3 on 2024-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_deal_message_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
