# Generated by Django 5.0.3 on 2024-03-21 19:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeetingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='General notes about the meeting.')),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meetings', to='daily.daily')),
            ],
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the commitment made by the dailymeetinglog.')),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Canceled', 'Canceled'), ('Blocked', 'Blocked'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='daily.dailymeetinglog')),
                ('meeting_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='daily.dailymeetinglog')),
            ],
        ),
    ]
